set LD_OBS_CONNECTOR_ROOT=C:\source\obs
set build_config=Release
set DEPS_BASE_PATH=%LD_OBS_CONNECTOR_ROOT%\deps
set QT_BASE_DIR=%LD_OBS_CONNECTOR_ROOT%\qt
set OBS_PATH=%LD_OBS_CONNECTOR_ROOT%\obs
set DEPS_PATH_32=%DEPS_BASE_PATH%\win32
set DEPS_PATH_64=%DEPS_BASE_PATH%\win64
set QTDIR32=%QT_BASE_DIR%\5.15.2\msvc2019
set QTDIR64=%QT_BASE_DIR%\5.15.2\msvc2019_64

